<?php

namespace Potelo\InterPhp\Api;

use Datetime;

class PixApi extends ApiRequest
{
    const BASE_PATH = self::DEFAULT_API_BASE . 'pix/v2/pix/';

    /**
     * Endpoint to get a Pix.
     * @see https://developers.bancointer.com.br/reference/get_pix-e2eid-1
     *
     * @param  string  $e2eId
     * @return mixed
     */
    public function get(string $e2eId)
    {
        $response = $this->getApi(self::BASE_PATH . $e2eId);

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Endpoint to get a list of Pix for a specific period, according to the parameters informed.
     * @see https://developers.bancointer.com.br/reference/get_pix-1
     *
     * @param  \DateTime  $after
     * @param  \DateTime  $before
     * @param  array  $filters
     * @return mixed
     */
    public function list(DateTime $after, DateTime $before, array $filters = [])
    {
        $filters = array_merge($filters, [
            'inicio' => $after->format('Y-m-d\TH:i:s\-03:00'),
            'fim' => $before->format('Y-m-d\TH:i:s\-03:00'),
        ]);

        $response = $this->getApi(self::BASE_PATH . '?' . http_build_query($filters));

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Endpoint to return a Pix.
     * @see https://developers.bancointer.com.br/reference/put_pix-e2eid-devolucao-id-1
     *
     * @param  string  $e2eId the ID of the Pix
     * @param  string  $id the ID generated by the client to identify the return
     * @param  float  $amount the amount to return
     * @param  array  $data the others data to be sent
     * @return mixed
     */
    public function returnPix(string $e2eId, string $id, float $amount, array $data = [])
    {
        $options = [
            'json' => array_merge($data, [
                'valor' => number_format($amount, 2, '.', ''),
            ]),
        ];

        $response = $this->putApi(self::BASE_PATH . $e2eId . '/devolucao/' . $id, $options);

        return json_decode($response->getBody()->getContents());
    }

    /**
     * Endpoint to get information about a Pix return.
     * @see https://developers.bancointer.com.br/reference/get_pix-e2eid-devolucao-id-1
     *
     * @param  string  $e2eId
     * @param  string  $id
     * @return mixed
     */
    public function getReturnPix(string $e2eId, string $id)
    {
        $response = $this->getApi(self::BASE_PATH . $e2eId . '/devolucao/' . $id);

        return json_decode($response->getBody()->getContents());
    }
}
